### ISSUE TITLE
Link incorrect on Additional Resources

### ISSUE THREAD

**Issue by kritikality** [AdobeDocs/analytics-learn.en#13]
Issue in ./help/analysis-workspace/attribution-iq/attribution-iq-in-calculated-metrics.md

!he Additional Resources > Feature Documentation link at the bottom of the page is not found.  

Please update the link

**Comment by mugdoor** [comment]
This has been fixed. Thanks for letting us know.
Doug



Doug Moore  |  Technical Marketing Engineer  |  Adobe, Inc. |  o.385.345.1176 | m.801.234.0502



From: Kristi Barrow ***@***.***>
Reply-To: "AdobeDocs/analytics-learn.en" ***@***.***>
Date: Monday, May 17, 2021 at 6:47 PM
To: "AdobeDocs/analytics-learn.en" ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AdobeDocs/analytics-learn.en] Link incorrect on Additional Resources (#13)


Issue in ./help/analysis-workspace/attribution-iq/attribution-iq-in-calculated-metrics.md

!he Additional Resources > Feature Documentation link at the bottom of the page is not found.

Please update the link
