### ISSUE TITLE
View Post-Processed Hits with the Experience Cloud Debugger help page no longer accurate

### ISSUE THREAD

**Issue by luckydad** [AdobeDocs/analytics-learn.en#15]
Issue in ./help/implementation/validating-and-troubleshooting/view-post-processed-hits-with-the-experience-cloud-debugger.md

Hi-
This help page:
https://experienceleague.adobe.com/docs/analytics-learn/tutorials/implementation/validating-and-troubleshooting/view-post-processed-hits-with-the-experience-cloud-debugger.html?lang=en
is no longer accurate.
1. The video features an out of date version of the debugger.
2. AND, the current debugger no longer has this feature of being able to view post-processed hits

(OR if that feature IS available it is VERY well hidden.)

See experiencecloud discussions on the following pages:

https://experienceleaguecommunities.adobe.com/t5/aep-debugger-ideas/post-processed-hits-data-in-adobe-debugger/idc-p/412622#M63

https://experienceleaguecommunities.adobe.com/t5/aep-debugger-ideas/support-post-processed-analytics-hits/idi-p/359554

Thanks, Michael

**Comment by mugdoor** [comment]
Michael,
Thanks for bringing this to my attention. I am removing the outdated video. I found out that even though this feature is not currently available on the new Platform debugger, it is on the road map and should be added soon. I don't have a date to give you, but it's coming!
Thanks,
Doug
