### ISSUE TITLE
Wrong transcript

### ISSUE THREAD

**Issue by AmeliusMarin** [AdobeDocs/analytics-learn.en#24]
Issue in ./help/analysis-workspace/building-freeform-tables/freeform-table-totals-in-analysis-workspace.md

The transcript for the video on this page is the wrong one. The video is done by Doug, but the transcript is for one of the videos by Jen Lasser.

**Comment by mugdoor** [comment]
Thanks for bringing this to our attention. The localization team has been notified, and it will be fixed.
